export const ROUTES = {
  LANDING: "/",
  REVENUE_CYCLE: "/revenue-cycle",
  HMO_MANAGEMENT: "/hmo-management",
  CLAIMS_PROCESSING: "/claims-processing",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_OF_SERVICE: "/terms-of-service",
  CLINICAL_ETHICS: "/clinical-ethics",
  SECURITY_WHITEPAPER: "/security-whitepaper",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  ONBOARDING: "/onboarding",
  PAYMENT_LINK: "/pay/:token",
  PAYMENT_CALLBACK_CARD: "/pay/callback/card",
  PAYMENT_CALLBACK_OPAY: "/pay/callback/opay",
  DASHBOARD: "/dashboard",
  PATIENTS: "/patients",
  PATIENT_DETAIL: "/patients/:patientId",
  BILLS: "/bills",
  BILLS_NEW: "/bills/new",
  BILL_DETAIL: "/bills/:billId",
  CLAIMS: "/claims",
  ANALYTICS: "/analytics",
  SETTINGS: "/settings",
} as const
